### ISSUE TITLE
[QUESTION] Reduce DB size 

### ISSUE THREAD

**Issue by hans2103** [tig-nl/gls-magento2#23]
**Question**
Ask your question in an arbitrary form without insulting someone. Please make sure it's worded well enough to be understood and remove this line.

sorting the DB tables by size both PostNL and GLS modules created by you take a huge amount of space. 
Combined they are over 1GB.
The third largest table is from another developer and consumes 60MB. Yours take 662MB and 502MB, combined over 1GB

What can be done to reduce this growing table?
![Schermafbeelding 2021-09-10 om 16 40 24](https://user-images.githubusercontent.com/639822/132871496-998a60ca-edd9-423a-a658-7fb468fda0b1.png)

**Comment by tig-jeffreybranderhorst** [comment]
Hey @hans2103 ,

We know these tables are big, that is because all the labels are saved in there. And that takes up a lot of space, especially if you have a lot of orders. You could delete labels of a year and older, but this is at your own risk.  This will make you lose your labels but if that does not matter you could try this. 

Have a great day,
Jeffrey
